[worker1]
worker1_ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[worker2]
worker2_ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[worker3]
worker3_ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[worker4]
worker4_ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa